package dev.xernas.photon.api.window.input;

import org.lwjgl.glfw.GLFW;

public enum Key {

    KEY_UNKNOWN(GLFW.GLFW_KEY_UNKNOWN, GLFW.GLFW_KEY_UNKNOWN),
    KEY_A(GLFW.GLFW_KEY_A, GLFW.GLFW_KEY_Q),
    KEY_Z(GLFW.GLFW_KEY_Z, GLFW.GLFW_KEY_W),
    KEY_E(GLFW.GLFW_KEY_E, GLFW.GLFW_KEY_E),
    KEY_R(GLFW.GLFW_KEY_R, GLFW.GLFW_KEY_R),
    KEY_T(GLFW.GLFW_KEY_T, GLFW.GLFW_KEY_T),
    KEY_Y(GLFW.GLFW_KEY_Y, GLFW.GLFW_KEY_Y),
    KEY_U(GLFW.GLFW_KEY_U, GLFW.GLFW_KEY_U),
    KEY_I(GLFW.GLFW_KEY_I, GLFW.GLFW_KEY_I),
    KEY_O(GLFW.GLFW_KEY_O, GLFW.GLFW_KEY_O),
    KEY_P(GLFW.GLFW_KEY_P, GLFW.GLFW_KEY_P),
    KEY_Q(GLFW.GLFW_KEY_Q, GLFW.GLFW_KEY_A),
    KEY_S(GLFW.GLFW_KEY_S, GLFW.GLFW_KEY_S),
    KEY_D(GLFW.GLFW_KEY_D, GLFW.GLFW_KEY_D),
    KEY_F(GLFW.GLFW_KEY_F, GLFW.GLFW_KEY_F),
    KEY_G(GLFW.GLFW_KEY_G, GLFW.GLFW_KEY_G),
    KEY_H(GLFW.GLFW_KEY_H, GLFW.GLFW_KEY_H),
    KEY_J(GLFW.GLFW_KEY_J, GLFW.GLFW_KEY_J),
    KEY_K(GLFW.GLFW_KEY_K, GLFW.GLFW_KEY_K),
    KEY_L(GLFW.GLFW_KEY_L, GLFW.GLFW_KEY_L),
    KEY_M(GLFW.GLFW_KEY_M, GLFW.GLFW_KEY_SEMICOLON),
    KEY_W(GLFW.GLFW_KEY_W, GLFW.GLFW_KEY_Z),
    KEY_X(GLFW.GLFW_KEY_X, GLFW.GLFW_KEY_X),
    KEY_C(GLFW.GLFW_KEY_C, GLFW.GLFW_KEY_C),
    KEY_V(GLFW.GLFW_KEY_V, GLFW.GLFW_KEY_V),
    KEY_B(GLFW.GLFW_KEY_B, GLFW.GLFW_KEY_B),
    KEY_N(GLFW.GLFW_KEY_N, GLFW.GLFW_KEY_N),
    KEY_SEMICOLON(GLFW.GLFW_KEY_SEMICOLON, GLFW.GLFW_KEY_M),
    KEY_ARROW_UP(GLFW.GLFW_KEY_UP, GLFW.GLFW_KEY_UP),
    KEY_ARROW_DOWN(GLFW.GLFW_KEY_DOWN, GLFW.GLFW_KEY_DOWN),
    KEY_ARROW_LEFT(GLFW.GLFW_KEY_LEFT, GLFW.GLFW_KEY_LEFT),
    KEY_ARROW_RIGHT(GLFW.GLFW_KEY_RIGHT, GLFW.GLFW_KEY_RIGHT),
    KEY_ENTER(GLFW.GLFW_KEY_ENTER, GLFW.GLFW_KEY_ENTER),
    KEY_BACKSPACE(GLFW.GLFW_KEY_BACKSPACE, GLFW.GLFW_KEY_BACKSPACE),
    KEY_ESCAPE(GLFW.GLFW_KEY_ESCAPE, GLFW.GLFW_KEY_ESCAPE),
    KEY_NUMPAD_0(GLFW.GLFW_KEY_KP_0, GLFW.GLFW_KEY_KP_0),
    KEY_NUMPAD_1(GLFW.GLFW_KEY_KP_1, GLFW.GLFW_KEY_KP_1),
    KEY_NUMPAD_2(GLFW.GLFW_KEY_KP_2, GLFW.GLFW_KEY_KP_2),
    KEY_NUMPAD_3(GLFW.GLFW_KEY_KP_3, GLFW.GLFW_KEY_KP_3),
    KEY_NUMPAD_4(GLFW.GLFW_KEY_KP_4, GLFW.GLFW_KEY_KP_4),
    KEY_NUMPAD_5(GLFW.GLFW_KEY_KP_5, GLFW.GLFW_KEY_KP_5),
    KEY_NUMPAD_6(GLFW.GLFW_KEY_KP_6, GLFW.GLFW_KEY_KP_6),
    KEY_NUMPAD_7(GLFW.GLFW_KEY_KP_7, GLFW.GLFW_KEY_KP_7),
    KEY_NUMPAD_8(GLFW.GLFW_KEY_KP_8, GLFW.GLFW_KEY_KP_8),
    KEY_NUMPAD_9(GLFW.GLFW_KEY_KP_9, GLFW.GLFW_KEY_KP_9),
    KEY_F1(GLFW.GLFW_KEY_F1, GLFW.GLFW_KEY_F1),
    KEY_F2(GLFW.GLFW_KEY_F2, GLFW.GLFW_KEY_F2),
    KEY_F3(GLFW.GLFW_KEY_F3, GLFW.GLFW_KEY_F3),
    KEY_F4(GLFW.GLFW_KEY_F4, GLFW.GLFW_KEY_F4),
    KEY_F5(GLFW.GLFW_KEY_F5, GLFW.GLFW_KEY_F5),
    KEY_F6(GLFW.GLFW_KEY_F6, GLFW.GLFW_KEY_F6),
    KEY_F7(GLFW.GLFW_KEY_F7, GLFW.GLFW_KEY_F7),
    KEY_F8(GLFW.GLFW_KEY_F8, GLFW.GLFW_KEY_F8),
    KEY_F9(GLFW.GLFW_KEY_F9, GLFW.GLFW_KEY_F9),
    KEY_F10(GLFW.GLFW_KEY_F10, GLFW.GLFW_KEY_F10),
    KEY_F11(GLFW.GLFW_KEY_F11, GLFW.GLFW_KEY_F11),
    KEY_F12(GLFW.GLFW_KEY_F12, GLFW.GLFW_KEY_F12),
    KEY_TAB(GLFW.GLFW_KEY_TAB, GLFW.GLFW_KEY_TAB),
    KEY_LEFT_SHIFT(GLFW.GLFW_KEY_LEFT_SHIFT, GLFW.GLFW_KEY_LEFT_SHIFT),
    KEY_RIGHT_SHIFT(GLFW.GLFW_KEY_RIGHT_SHIFT, GLFW.GLFW_KEY_RIGHT_SHIFT),
    KEY_SPACE(GLFW.GLFW_KEY_SPACE, GLFW.GLFW_KEY_SPACE),
    KEY_LEFT_CONTROL(GLFW.GLFW_KEY_LEFT_CONTROL, GLFW.GLFW_KEY_LEFT_CONTROL),
    KEY_RIGHT_CONTROL(GLFW.GLFW_KEY_RIGHT_CONTROL, GLFW.GLFW_KEY_RIGHT_CONTROL),

    MOUSE_LEFT(GLFW.GLFW_MOUSE_BUTTON_LEFT, GLFW.GLFW_MOUSE_BUTTON_LEFT),
    MOUSE_RIGHT(GLFW.GLFW_MOUSE_BUTTON_RIGHT, GLFW.GLFW_MOUSE_BUTTON_RIGHT),
    MOUSE_MIDDLE(GLFW.GLFW_MOUSE_BUTTON_MIDDLE, GLFW.GLFW_MOUSE_BUTTON_MIDDLE),
    MOUSE_BUTTON_4(GLFW.GLFW_MOUSE_BUTTON_4, GLFW.GLFW_MOUSE_BUTTON_4),
    MOUSE_BUTTON_5(GLFW.GLFW_MOUSE_BUTTON_5, GLFW.GLFW_MOUSE_BUTTON_5);

    private final int azerty;
    private final int qwerty;

    Key(int azerty, int qwerty) {
        this.azerty = azerty;
        this.qwerty = qwerty;
    }

    public static Key fromCode(int code, boolean azerty) {
        for (Key key : values()) {
            if ((azerty ? key.getQwerty() : key.getAzerty()) == code) {
                return key;
            }
        }
        return Key.KEY_UNKNOWN;
    }

    public int getAzerty() {
        return azerty;
    }

    public int getQwerty() {
        return qwerty;
    }

}
